name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2 #this will install Node and npm on Ubuntu
        with:
          node-version: "16.5.0"
      - run: npm install
      - run: npm run validate
